### ISSUE TITLE
Android 14 SDK limitation INSTALL_FAILED_DEPRECATED_SDK_VERSION

### ISSUE THREAD

**Issue by robinknaapen** [henrichg/PPPPutSettings#4]
Installation fails due to new Android 14 limitations: https://bayton.org/android/android-14-minimum-sdk/#whats-changing

I read the comment in [dependencies.gradle](https://github.com/henrichg/PPPPutSettings/blob/main/dependencies.gradle#L7)

As read in the linked article, adb could probably be used to overcome this (haven't tested this yet)

Either way, a note in the README would be a nice touch

**Comment by henrichg** [comment]
It i in README.md.

If it is not possible to install PPPPutSettings from GitHub or other sources directly on the device, then it can be installed from PC.

Show how

**Comment by henrichg** [comment]
https://github.com/henrichg/PPPPutSettings/blob/main/docs/install_apk_from_pc.md

**Comment by henrichg** [comment]
https://github.com/henrichg/PPPPutSettings/blob/devel/docs/install_apk_from_pc.md

**Comment by robinknaapen** [comment]
Thanks for the reference 🙏
